<?php
return [
    ['nome' => 'Futebol', 'tipo_id' => 1],
    ['nome' => 'Basquete', 'tipo_id' => 1],
    ['nome' => 'Vôlei', 'tipo_id' => 1],
    ['nome' => 'Handebol', 'tipo_id' => 1],
    ['nome' => 'Natação', 'tipo_id' => 1],
    ['nome' => 'Atletismo', 'tipo_id' => 1],
    ['nome' => 'Ginástica Olímpica', 'tipo_id' => 1],
    ['nome' => 'Judô', 'tipo_id' => 1],
    ['nome' => 'Karatê', 'tipo_id' => 1],
    ['nome' => 'Taekwondo', 'tipo_id' => 1],
    ['nome' => 'Dança Esportiva', 'tipo_id' => 1],
    ['nome' => 'Xadrez', 'tipo_id' => 1],
    ['nome' => 'Tênis de Mesa', 'tipo_id' => 1],
    ['nome' => 'Badminton', 'tipo_id' => 1],
    ['nome' => 'Hóquei', 'tipo_id' => 1],
    ['nome' => 'Rugby', 'tipo_id' => 1],
    ['nome' => 'Beisebol', 'tipo_id' => 1],
    ['nome' => 'Softbol', 'tipo_id' => 1],
    ['nome' => 'Golfe', 'tipo_id' => 1],
    ['nome' => 'Polo Aquático', 'tipo_id' => 1],
    ['nome' => 'Tênis', 'tipo_id' => 1],
    ['nome' => 'Ciclismo', 'tipo_id' => 1],
    ['nome' => 'Surfe', 'tipo_id' => 1],
    ['nome' => 'Skate', 'tipo_id' => 1],
    ['nome' => 'Escalada', 'tipo_id' => 1],
    ['nome' => 'Ginástica Artística', 'tipo_id' => 1],
    ['nome' => 'Hipismo', 'tipo_id' => 1],
    ['nome' => 'Vela', 'tipo_id' => 1],
    ['nome' => 'Remo', 'tipo_id' => 1],
    ['nome' => 'Esgrima', 'tipo_id' => 1],
    ['nome' => 'Halterofilismo', 'tipo_id' => 1],
    ['nome' => 'Boxe', 'tipo_id' => 1],
    ['nome' => 'Arco e Flecha', 'tipo_id' => 1],
    ['nome' => 'Tiro com Arco', 'tipo_id' => 1],
    ['nome' => 'Boliche', 'tipo_id' => 1],
    ['nome' => 'Canoagem', 'tipo_id' => 1],
    ['nome' => 'Futebol Americano', 'tipo_id' => 1],
    ['nome' => 'Ginástica Rítmica', 'tipo_id' => 1],
    ['nome' => 'Patinagem Artística', 'tipo_id' => 1],
    ['nome' => 'Pentatlo Moderno', 'tipo_id' => 1],
    ['nome' => 'Squash', 'tipo_id' => 1],
    ['nome' => 'Tiro Esportivo', 'tipo_id' => 1],
    ['nome' => 'Triatlo', 'tipo_id' => 1],

    ['nome' => 'Teatro', 'tipo_id' => 2],
    ['nome' => 'Dança', 'tipo_id' => 2],
    ['nome' => 'Música', 'tipo_id' => 2],
    ['nome' => 'Artes Visuais', 'tipo_id' => 2],
    ['nome' => 'Pintura', 'tipo_id' => 2],
    ['nome' => 'Escultura', 'tipo_id' => 2],
    ['nome' => 'Desenho', 'tipo_id' => 2],
    ['nome' => 'Canto', 'tipo_id' => 2],
    ['nome' => 'Instrumento Musical', 'tipo_id' => 2],
    ['nome' => 'Cinema e Audiovisual', 'tipo_id' => 2],
    ['nome' => 'Fotografia', 'tipo_id' => 2],
    ['nome' => 'Design', 'tipo_id' => 2],
    ['nome' => 'Moda', 'tipo_id' => 2],
    ['nome' => 'Artesanato', 'tipo_id' => 2],
    ['nome' => 'Gastronomia', 'tipo_id' => 2],
    ['nome' => 'Poesia', 'tipo_id' => 2],
    ['nome' => 'Literatura', 'tipo_id' => 2],
    ['nome' => 'Cultura e Folclore', 'tipo_id' => 2],

    ['nome' => 'Apoio a Idosos', 'tipo_id' => 3],
    ['nome' => 'Apoio a Crianças', 'tipo_id' => 3],
    ['nome' => 'Apoio a Pessoas com Deficiência', 'tipo_id' => 3],
    ['nome' => 'Apoio a Animais', 'tipo_id' => 3],
    ['nome' => 'Ações Ambientais', 'tipo_id' => 3],
    ['nome' => 'Educação Social', 'tipo_id' => 3],
    ['nome' => 'Arrecadação de Alimentos', 'tipo_id' => 3],
    ['nome' => 'Campanhas de Saúde', 'tipo_id' => 3],
    ['nome' => 'Atividades Culturais em Comunidades Carentes', 'tipo_id' => 3],
    ['nome' => 'Aulas de Reforço Escolar', 'tipo_id' => 3],
    ['nome' => 'Visitas a Hospitais e Abrigos', 'tipo_id' => 3],
    ['nome' => 'Trabalho em ONGs', 'tipo_id' => 3],
    ['nome' => 'Conscientização Social', 'tipo_id' => 3],

    ['nome' => 'Clube de Debate em Português', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate em Inglês', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate em Espanhol', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate de Políticas Públicas', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Meio Ambiente', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Direitos Humanos', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Questões Sociais', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Filosofia', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre História', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Ciência e Tecnologia', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Literatura', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Economia', 'tipo_id' => 4],
    ['nome' => 'Clube de Debate sobre Relações Internacionais', 'tipo_id' => 4],

    ['nome' => 'Clube de Leitura', 'tipo_id' => 5],
    ['nome' => 'Biblioteca Comunitária', 'tipo_id' => 5],
    ['nome' => 'Oficina de Escrita Criativa', 'tipo_id' => 5],
    ['nome' => 'Maratona de Leitura', 'tipo_id' => 5],
    ['nome' => 'Leitura de Poesia', 'tipo_id' => 5],
    ['nome' => 'Contação de Histórias', 'tipo_id' => 5],
    ['nome' => 'Leitura em Grupo', 'tipo_id' => 5],
    ['nome' => 'Clube de Fãs de Literatura', 'tipo_id' => 5],
    ['nome' => 'Leitura em Voz Alta', 'tipo_id' => 5],
    ['nome' => 'Rodas de Leitura', 'tipo_id' => 5],
    ['nome' => 'Leitura de Clássicos da Literatura', 'tipo_id' => 5],
    ['nome' => 'Leitura de Contos e Crônicas', 'tipo_id' => 5],
    ['nome' => 'Clube de Leitura em Outros Idiomas', 'tipo_id' => 5],

    ['nome' => 'Clube de Empreendedorismo', 'tipo_id' => 6],
    ['nome' => 'Feira de Empreendedorismo', 'tipo_id' => 6],
    ['nome' => 'Oficina de Planejamento de Negócios', 'tipo_id' => 6],
    ['nome' => 'Mentoria para Startups', 'tipo_id' => 6],
    ['nome' => 'Simulação de Negócios', 'tipo_id' => 6],
    ['nome' => 'Palestras sobre Empreendedorismo', 'tipo_id' => 6],
    ['nome' => 'Workshop de Inovação', 'tipo_id' => 6],
    ['nome' => 'Hackathon Empreendedor', 'tipo_id' => 6],
    ['nome' => 'Desafio de Negócios', 'tipo_id' => 6],
    ['nome' => 'Projeto de Empreendedorismo Social', 'tipo_id' => 6],
    ['nome' => 'Feira de Produtos Artesanais', 'tipo_id' => 6],
    ['nome' => 'Iniciação Científica Empreendedora', 'tipo_id' => 6],
    ['nome' => 'Ideathon', 'tipo_id' => 6],

    ['nome' => 'Clube de Ciências', 'tipo_id' => 7],
    ['nome' => 'Feira de Ciências', 'tipo_id' => 7],
    ['nome' => 'Olimpíada de Ciências', 'tipo_id' => 7],
    ['nome' => 'Experimentos Científicos', 'tipo_id' => 7],
    ['nome' => 'Observação Astronômica', 'tipo_id' => 7],
    ['nome' => 'Workshop de Ciências', 'tipo_id' => 7],
    ['nome' => 'Excursão Científica', 'tipo_id' => 7],
    ['nome' => 'Clube de Astronomia', 'tipo_id' => 7],
    ['nome' => 'Clube de Biologia', 'tipo_id' => 7],
    ['nome' => 'Clube de Química', 'tipo_id' => 7],
    ['nome' => 'Clube de Física', 'tipo_id' => 7],

    ['nome' => 'Clube de Matemática', 'tipo_id' => 8],
    ['nome' => 'Olimpíada de Matemática', 'tipo_id' => 8],
    ['nome' => 'Torneio de Cálculo Mental', 'tipo_id' => 8],
    ['nome' => 'Maratona de Problemas', 'tipo_id' => 8],
    ['nome' => 'Workshop de Matemática', 'tipo_id' => 8],
    ['nome' => 'Competições Matemáticas', 'tipo_id' => 8],
    ['nome' => 'Clube de Jogos Matemáticos', 'tipo_id' => 8],
    ['nome' => 'Desafios Matemáticos', 'tipo_id' => 8],
    ['nome' => 'Projeto de Pesquisa Matemática', 'tipo_id' => 8],
    ['nome' => 'Oficina de Geometria', 'tipo_id' => 8],
    ['nome' => 'Clube de Estatística', 'tipo_id' => 8],
    ['nome' => 'Feira de Matemática', 'tipo_id' => 8],
    ['nome' => 'Estudo de Teoremas e Provas', 'tipo_id' => 8],

    ['nome' => 'Clube de História', 'tipo_id' => 9],
    ['nome' => 'Simulação Histórica', 'tipo_id' => 9],
    ['nome' => 'Palestras sobre História', 'tipo_id' => 9],
    ['nome' => 'Debates Históricos', 'tipo_id' => 9],
    ['nome' => 'Exposições Temáticas', 'tipo_id' => 9],
    ['nome' => 'Pesquisa e Análise de Documentos', 'tipo_id' => 9],
    ['nome' => 'Visitas a Museus e Sítios Arqueológicos', 'tipo_id' => 9],
    ['nome' => 'Recriação de Épocas e Civilizações', 'tipo_id' => 9],
    ['nome' => 'Filmes e Documentários Históricos', 'tipo_id' => 9],
    ['nome' => 'Projeto de História Local', 'tipo_id' => 9],
    ['nome' => 'Viagens Históricas', 'tipo_id' => 9],
    ['nome' => 'Estudo de Grandes Personalidades da História', 'tipo_id' => 9],
    ['nome' => 'Clube de Arqueologia', 'tipo_id' => 9],

    ['nome' => 'Clube de Geografia', 'tipo_id' => 10],
    ['nome' => 'Simulação de Modelos Geográficos', 'tipo_id' => 10],
    ['nome' => 'Palestras sobre Geografia', 'tipo_id' => 10],
    ['nome' => 'Debates Geográficos', 'tipo_id' => 10],
    ['nome' => 'Exposições Temáticas de Geografia', 'tipo_id' => 10],
    ['nome' => 'Pesquisa e Análise de Mapas e Cartografias', 'tipo_id' => 10],
    ['nome' => 'Visitas a Espaços Geográficos Relevantes', 'tipo_id' => 10],
    ['nome' => 'Estudo de Ecossistemas e Biomas', 'tipo_id' => 10],
    ['nome' => 'Filmes e Documentários Geográficos', 'tipo_id' => 10],
    ['nome' => 'Projeto de Geografia Humana', 'tipo_id' => 10],
    ['nome' => 'Viagens Geográficas', 'tipo_id' => 10],
    ['nome' => 'Estudo de Questões Ambientais', 'tipo_id' => 10],
    ['nome' => 'Clube de Geopolítica', 'tipo_id' => 10],

    ['nome' => 'Estudos de Religião', 'tipo_id' => 11,],

    ['nome' => 'Clube de Filosofia', 'tipo_id' => 12],
    ['nome' => 'Debate Filosófico', 'tipo_id' => 12],
    ['nome' => 'Café Filosófico', 'tipo_id' => 12],
    ['nome' => 'Leitura e Discussão de Livros Filosóficos', 'tipo_id' => 12],
    ['nome' => 'Filmes e Documentários Filosóficos', 'tipo_id' => 12],
    ['nome' => 'Seminários de Ética', 'tipo_id' => 12],
    ['nome' => 'Estudo de Grandes Filósofos', 'tipo_id' => 12],
    ['nome' => 'Filosofia Aplicada à Vida Cotidiana', 'tipo_id' => 12],
    ['nome' => 'Projetos de Pensamento Crítico', 'tipo_id' => 12],
    ['nome' => 'Questões Filosóficas Contemporâneas', 'tipo_id' => 12],
    ['nome' => 'Oficina de Lógica', 'tipo_id' => 12],
    ['nome' => 'Filosofia Oriental', 'tipo_id' => 12],
    ['nome' => 'Filosofia e Arte', 'tipo_id' => 12],

    ['nome' => 'Clube de Sociologia', 'tipo_id' => 13],
    ['nome' => 'Debate Sociológico', 'tipo_id' => 13],
    ['nome' => 'Café Sociológico', 'tipo_id' => 13],
    ['nome' => 'Leitura e Discussão de Livros Sociológicos', 'tipo_id' => 13],
    ['nome' => 'Filmes e Documentários Sociológicos', 'tipo_id' => 13],
    ['nome' => 'Seminários sobre Temas Sociais', 'tipo_id' => 13],
    ['nome' => 'Estudo de Grandes Sociólogos', 'tipo_id' => 13],
    ['nome' => 'Sociologia Aplicada à Vida Cotidiana', 'tipo_id' => 13],
    ['nome' => 'Projetos de Pesquisa Social', 'tipo_id' => 13],
    ['nome' => 'Questões Sociológicas Contemporâneas', 'tipo_id' => 13],
    ['nome' => 'Oficina de Análise de Dados Sociais', 'tipo_id' => 13],
    ['nome' => 'Sociologia e Cultura', 'tipo_id' => 13],
    ['nome' => 'Sociologia e Política', 'tipo_id' => 13],

    ['nome' => 'Clube de Psicologia', 'tipo_id' => 14],
    ['nome' => 'Oficina de Autoconhecimento', 'tipo_id' => 14],
    ['nome' => 'Estudo de Teorias Psicológicas', 'tipo_id' => 14],
    ['nome' => 'Filmes e Documentários sobre Psicologia', 'tipo_id' => 14],
    ['nome' => 'Projeto de Apoio Psicológico', 'tipo_id' => 14],
    ['nome' => 'Seminários sobre Temas Psicológicos', 'tipo_id' => 14],
    ['nome' => 'Workshop sobre Inteligência Emocional', 'tipo_id' => 14],
    ['nome' => 'Clube de Psicanálise', 'tipo_id' => 14],
    ['nome' => 'Grupo de Estudos de Psicologia Social', 'tipo_id' => 14],

    ['nome' => 'Clube de Informática', 'tipo_id' => 15],
    ['nome' => 'Oficina de Programação', 'tipo_id' => 15],
    ['nome' => 'Competições de Programação', 'tipo_id' => 15],
    ['nome' => 'Criação de Websites', 'tipo_id' => 15],
    ['nome' => 'Desenvolvimento de Jogos', 'tipo_id' => 15],
    ['nome' => 'Robótica com Arduino', 'tipo_id' => 15],
    ['nome' => 'Introdução à Inteligência Artificial', 'tipo_id' => 15],
    ['nome' => 'Workshop de Segurança Digital', 'tipo_id' => 15],
    ['nome' => 'Clube de Ciência de Dados', 'tipo_id' => 15],
    ['nome' => 'Oficina de Design Gráfico', 'tipo_id' => 15],

    ['nome' => 'Clube de Robótica', 'tipo_id' => 16],
    ['nome' => 'Competições de Robótica', 'tipo_id' => 16],
    ['nome' => 'Oficina de Montagem de Robôs', 'tipo_id' => 16],
    ['nome' => 'Robótica com LEGO Mindstorms', 'tipo_id' => 16],
    ['nome' => 'Workshop de Programação de Robôs', 'tipo_id' => 16],
    ['nome' => 'Desafios de Robótica', 'tipo_id' => 16],
    ['nome' => 'Projeto de Automação Residencial', 'tipo_id' => 16],
    ['nome' => 'Clube de Drones', 'tipo_id' => 16],
    ['nome' => 'Robótica Educacional', 'tipo_id' => 16],
    ['nome' => 'Oficina de Robótica Colaborativa', 'tipo_id' => 16],

    ['nome' => 'Palestra Motivacional', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Empreendedorismo', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Saúde Mental', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Tecnologia e Inovação', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Meio Ambiente', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Inclusão e Diversidade', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Liderança', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Ciência e Pesquisa', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre Arte e Cultura', 'tipo_id' => 17],
    ['nome' => 'Palestra sobre História e Sociedade', 'tipo_id' => 17],

    ['nome' => 'Clube de Música', 'tipo_id' => 18],
    ['nome' => 'Clube de Artes', 'tipo_id' => 18],
    ['nome' => 'Aulas de Idiomas', 'tipo_id' => 18],
    ['nome' => 'Atividades de Dança', 'tipo_id' => 18],
    ['nome' => 'Clube de Teatro', 'tipo_id' => 18],
    ['nome' => 'Aulas de Yoga e Meditação', 'tipo_id' => 18],
    ['nome' => 'Atividades Esportivas Alternativas', 'tipo_id' => 18],
    ['nome' => 'Clube de Debate sobre Atualidades', 'tipo_id' => 18],
    ['nome' => 'Grupo de Amigos dos Animais', 'tipo_id' => 18],
    ['nome' => 'Projeto de Sustentabilidade', 'tipo_id' => 18],
    ['nome' => 'Clube de Cinema', 'tipo_id' => 18],
    ['nome' => 'Clube de Fotografia', 'tipo_id' => 18],
    ['nome' => 'Atividades de Culinária', 'tipo_id' => 18],
    ['nome' => 'Grupo de Estudo de Literatura Fantástica', 'tipo_id' => 18],
    ['nome' => 'Clube de Jardinagem', 'tipo_id' => 18],
    ['nome' => 'Atividades de Astronomia Amadora', 'tipo_id' => 18],
    ['nome' => 'Clube de Jogos de Tabuleiro', 'tipo_id' => 18],
    ['nome' => 'Projeto de Inovação Tecnológica', 'tipo_id' => 18],
    ['nome' => 'Clube de Criação e Edição de Vídeos', 'tipo_id' => 18],
    ['nome' => 'Atividades de Orientação Vocacional', 'tipo_id' => 18],
];
