<?php
return [
    ['categoria' => 'Ação e Aventura'],
    ['categoria' => 'Arte e Música'],
    ['categoria' => 'Autoajuda'],
    ['categoria' => 'Biografias e Memórias'],
    ['categoria' => 'Ciência e Tecnologia'],
    ['categoria' => 'Clássicos'],
    ['categoria' => 'Comics e Mangás'],
    ['categoria' => 'Contos e Crônicas'],
    ['categoria' => 'Educação e Didáticos'],
    ['categoria' => 'Esoterismo'],
    ['categoria' => 'Esportes e Lazer'],
    ['categoria' => 'Ficção Científica e Fantasia'],
    ['categoria' => 'Filosofia'],
    ['categoria' => 'História do Brasil'],
    ['categoria' => 'História Geral'],
    ['categoria' => 'Horror e Suspense'],
    ['categoria' => 'Humor'],
    ['categoria' => 'Infantojuvenis'],
    ['categoria' => 'Literatura Brasileira'],
    ['categoria' => 'Literatura Estrangeira'],
    ['categoria' => 'Medicina e Saúde'],
    ['categoria' => 'Negócios e Economia'],
    ['categoria' => 'Poesia'],
    ['categoria' => 'Policial e Mistério'],
    ['categoria' => 'Política'],
    ['categoria' => 'Psicologia'],
    ['categoria' => 'Religião e Espiritualidade'],
    ['categoria' => 'Romance'],
    ['categoria' => 'Terror'],
    ['categoria' => 'Viagem'],
];
