<?php
return [

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 60],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Ciências', 'carga_horaria' => 50],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Inglês', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 80],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Biologia', 'carga_horaria' => 60],
    ['nome' => 'Química', 'carga_horaria' => 60],
    ['nome' => 'Física', 'carga_horaria' => 60],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Inglês', 'carga_horaria' => 40],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],

    ['nome' => 'Matemática', 'carga_horaria' => 80],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Biologia', 'carga_horaria' => 60],
    ['nome' => 'Química', 'carga_horaria' => 60],
    ['nome' => 'Física', 'carga_horaria' => 60],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Inglês', 'carga_horaria' => 40],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Sociologia', 'carga_horaria' => 40],
    ['nome' => 'Filosofia', 'carga_horaria' => 40],

    ['nome' => 'Matemática', 'carga_horaria' => 80],
    ['nome' => 'Português', 'carga_horaria' => 80],
    ['nome' => 'Biologia', 'carga_horaria' => 60],
    ['nome' => 'Química', 'carga_horaria' => 60],
    ['nome' => 'Física', 'carga_horaria' => 60],
    ['nome' => 'História', 'carga_horaria' => 40],
    ['nome' => 'Geografia', 'carga_horaria' => 40],
    ['nome' => 'Inglês', 'carga_horaria' => 40],
    ['nome' => 'Artes', 'carga_horaria' => 30],
    ['nome' => 'Educação Física', 'carga_horaria' => 30],
    ['nome' => 'Sociologia', 'carga_horaria' => 40],
    ['nome' => 'Filosofia', 'carga_horaria' => 40],
    ['nome' => 'Literatura', 'carga_horaria' => 40],
    ['nome' => 'Redação', 'carga_horaria' => 40],
];
